# Generated by Django 5.2.5 on 2025-08-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='nombreCorto',
            field=models.SlugField(help_text='Siglas de la oficina', max_length=10, unique=True, verbose_name='Nombre corto'),
        ),
    ]
